# Project information
site_name: 'Sispop Docs'
site_url: 'https://docs.sispop.site'

# Repository
repo_name: 'sispop-docs'
repo_url: 'https://github.com/sispop-dev/sispop-docs'

# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
     accent: 'green'
  direction: 'ltr'
  feature:
    tabs: true
  font: false
  favicon: 'Sispop_favicon32x32.png'
  logo: 'logo.svg'

nav:
- 'Home': 'index.md'
- 'Introduction': 'Introduction/SispopNetwork.md'
- 'Getting Started': 'Introduction/GettingStarted.md'
- 'FAQ': 'FAQ.md'

- Wallets:
  - 'Overview' : 'Wallets/WalletsOverview.md'
  - 'Which wallet should I use?' : 'Wallets/WhatWalletToUse.md'

  - Addresses:
    - 'Main Address': 'Wallets/Addresses/MainAddress.md'
    - 'Sub Address': 'Wallets/Addresses/SubAddress.md'
    - 'Integrated Address': 'Wallets/Addresses/IntegratedAddress.md'
#  - Web Wallet (SispopLocker):
#      - 'Troubleshooting Web Wallet' : 'Wallets/WebWallet/TroubleshootWebWallet.md'
#      - Guides:
#        - 'to be added': 'Wallets/WebWallet/placeholder.md'
  - 'Multsignature': 'Wallets/Multisignature.md'

  - Guides:
        - 'Electron Gui Setup': 'Wallets/GuiWallet/sispop-electron-guide.md'
#        - 'Gui Setup': 'Wallets/GuiWallet/sispop-gui-guide.md'
        - 'Gui Staking Guide': 'ServiceNodes/GUIStakingGuide.md'
        - 'Mobile Wallet Restore': 'Wallets/MobileWallet/RestoreMobileWalletGuide.md'
        - 'CLI Mac Setup': 'Wallets/CliWallet/sispop-wallet-cliMacSetup.md'
        - 'CLI Wallet Commands': 'Wallets/CliWallet/WalletCommands.md'
        - 'CLI Restoring Wallet from Seed': 'Wallets/CliWallet/WalletRestoreSeed.md'
        - 'CLI Restoring Wallet from Keys': 'Wallets/CliWallet/WalletRestoreKeys.md'
        - Multisig:
           - '2/2 Multisig': 'Wallets/CliWallet/2of2Multisig.md'
           - '2/3 Multisig': 'Wallets/CliWallet/2of3Multisig.md'
           - 'M/N Multsig': 'Wallets/CliWallet/MofNMultisig.md'

# Outdated, moved to POS 
#- Mining:
#    - 'Overview': 'Mining/MiningOverview.md'
#    - 'ASIC Resistance': 'Mining/ASICResistance.md'
#    - Guides:
#      - 'XMR-Stak Mining': 'Mining/XMR-StakGuide.md'
#      - 'XMR-Stak Linux Mining': 'Mining/XMR-Stak-Linux-Guide.md'
#      - 'XMRig Mining': 'Mining/XMRig-Guide.md'
#      - 'Mining With a SBC': 'Mining/Mining-With-SBC.md'

- Service Nodes:
    - 'Overview': 'ServiceNodes/SNOverview.md'
#    - 'Service Node Functions': 'ServiceNodes/ServiceNodeFunctions.md'
    - 'Staking Requirement': 'ServiceNodes/StakingRequirement.md'
    - 'Deregistration Rules': 'ServiceNodes/DeregistrationRules.md'
#    - 'Infinite Staking Primer': 'ServiceNodes/InfiniteStakingPrimer.md'
    - Guides:
#      - 'Service Node Full Guide': 'ServiceNodes/SNFullGuide.md'
#      - 'Legacy to Launcher Update Guide': 'ServiceNodes/UpdateGuide.md'
      - 'Service Node Setup Guide': 'ServiceNodes/DebianPackageGuide.md'
      - 'Sispop-Launcher to Debian Update Guide': 'ServiceNodes/LauncherToDeb.md'
      - 'Service Node RPC Guide': 'Developer/SNRPCGuide.md'
      - 'Gui Staking Guide': 'ServiceNodes/GUIStakingGuide.md'
#      - 'Launcher Config File': 'ServiceNodes/launcherconfig.md'
      - 'Service Node Legacy Guide': 'ServiceNodes/SNFullGuideLegacy.md'
      - 'Service Node TESTNET Guide': 'ServiceNodes/StorageServerGuide-Testnet.md'
    - Troubleshooting:
      - 'Port 30000 Not Open': 'ServiceNodes/OpenPort30000.md'

- Sispopnet:
    - 'Overview': 'Sispopnet/SispopnetOverview.md'
    - 'Public Testing Overview': 'Sispopnet/Guides/PublicTestingGuide.md'
    - 'SNApps': 'Sispopnet/SNApps.md'
    - 'LLARP': 'Sispopnet/LLARP.md'
#    - 'Developers': 'Sispopnet/DeveloperInfo.md'

    - Guides:
        - 'Linux GUI Guide': 'Sispopnet/Guides/SispopnetGuiGuide.md'
        - 'macOS Gui Guide': 'Sispopnet/Guides/sispopnet-mac-guide.md'
        - 'Exit Provider Guide': 'Sispopnet/Guides/ExitProvider.md'
        - 'Anonymous Reverse SSH Guide': 'Sispopnet/Guides/ReverseSSHGuide.md'
        - 'Linux Command-line Guide': 'Sispopnet/Guides/sispopnet-linux-guide.md'
#        - 'Sispopnet Windows Guide': 'Sispopnet/Guides/sispopnet-windows-guide.md'
        - 'Linux - Build-It-Yourself': 'Sispopnet/Guides/Install.md'
        - 'Accessing SNApps': 'Sispopnet/Guides/AccessingSNApps.md'
        - 'Joining a Sispopnet IRC Chat': 'Sispopnet/Guides/SispopnetIRC.md'
        - 'Hosting SNApps': 'Sispopnet/Guides/HostingSNApps.md'
#        - 'Route through Exit Node': 'Sispopnet/Guides/RouteThroughExitNode.md'
        - 'Sispopnet config files': 'Sispopnet/Guides/SispopnetConfig.md'
        - 'Set up a Sispopnet Router': 'Sispopnet/Guides/SispopnetRouter.md'
        - 'Exit Nodes': 'Sispopnet/Guides/ExitNode.md'

- Session:
    - 'Overview': 'SispopServices/Messenger/Session.md'
    - 'Sispop Name System': 'SispopServices/Messenger/SispopNameSystem.md'
    - 'Threat Models': 'SispopServices/Messenger/threat_model.md'
    - 'Infrastructure': 'SispopServices/Messenger/infrastructure.md'
    - 'Message Routing': 'SispopServices/Messenger/message_routing.md'
    - 'Group Chats': 'SispopServices/Messenger/group_chats.md'
    - 'Testing': 'SispopServices/Messenger/testing.md'
    - 'Multi-Device': 'SispopServices/Messenger/multidevice.md'
    - 'Client Side Protection': 'SispopServices/Messenger/client_side_protection.md'
    - 'Attachments': 'SispopServices/Messenger/attachments.md'
    - Guides:
        - 'Register Session/Wallet names': 'SispopServices/Messenger/HowToRegisterSessionNames.md'
        - 'Multi-Device Setup': 'SispopServices/Messenger/multi_device_setup.md'
        - 'OpenGroup Setup': 'SispopServices/Messenger/opengroup_setup.md'
        - 'Join Open Group on Mobile': 'SispopServices/Messenger/JoinOpenGroupMobile.md'
        - 'Join Open Group on Desktop': 'SispopServices/Messenger/JoinOpenGroupDesktop.md'

- Blink:
    - 'Blink': 'SispopServices/Blink.md'
- Checkpointing:
    - 'Checkpointing LIP': 'Advanced/CheckpointingLip3.md'
    - 'Safely Receiving Sispop': 'Advanced/CheckpointingUpdate.md'
#- Pulse:
#    - 'Advanced/PulseLip5.md'

- Advanced:
    - Developer:
       - 'Service Node RPC Guide': 'Developer/SNRPCGuide.md'
#       - 'Daemon RPC Guide - Old': 'Developer/DaemonRPCGuide.md'
       - 'Daemon RPC Guide - Beta': 'Developer/DaemonRPCBeta.md'
#       - 'Wallet RPC Guide - Old': 'Developer/WalletRPCGuide.md'
       - 'Wallet RPC Guide - Beta': 'Developer/WalletRPCBeta.md'
       - 'Developer FAQ': 'Developer/FAQ.md'

    - Sispop Services:
       - 'Overview': 'SispopServices/SispopServicesOverview.md'
       - 'Blink': 'SispopServices/Blink.md'

    - Attack Prevention:
       - 'Denial of Service Attacks': 'Advanced/DenialofServiceAttacks.md'
       - 'IP and Packet Blocking': 'Advanced/IPandPacketBlocking.md'
       - 'Swarm Flagging': 'Advanced/SwarmFlagging.md'

    - Contributing:
       - 'How to Contribute to SispopDocs': 'Contributing/HowToContributeToSispopDocs.md'
       - 'Vulnerability Response': 'Contributing/VULNERABILITY_RESPONSE_SISPOP.md'
       - 'Github Issue Template Example': 'Contributing/Issue_Template.md'

    - Governance:
       - 'Overview': 'Governance/Governance.md'
       - 'The Sispop Foundation': 'Governance/TheSispopFoundation.md'
       - 'Sispop Funding System': 'Governance/SispopFundingSystem.md'

    - 'Cryptoeconomics' : 'Advanced/Cryptoeconomics.md'
    - 'Sybil Resistance' : 'Advanced/SybilResistance.md'
    - 'Dynamic Block Size': 'Advanced/DynamicBlockSize.md'
    - 'CryptoNote Elements': 'Advanced/CryptoNoteElements.md'
    - 'sispopd' : 'Advanced/sispopd.md'

    - Guides:
#        - 'Using Sispopnet': 'Advanced/UsingSispopnet.md'
        - 'Using Tor': 'Advanced/UsingTor.md'
        - 'Debugging': 'Advanced/Debugging.md'
        - 'Accepting Sispop for Merchants and Exchanges': 'Advanced/AcceptingSispop.md'

# Customization
extra_css:
  - CSS/style.css
  - CSS/font.css

extra_javascript:
  - JAVASCRIPT/links.js
  - JAVASCRIPT/style.js

extra:
  social:
    - type: 'github'
      link: 'https://github.com/sispop-dev'
    - type: 'twitter'
      link: 'https://twitter.com/sispop_'
    - type: 'telegram'
      link: 'https://t.me/Sispop'
    - type: 'reddit'
      link: 'https://www.reddit.com/r/SispopProject'
    - type: 'youtube'
      link: 'https://www.youtube.com/sispopnetwork'
    - type: 'facebook'
      link: 'https://www.facebook.com/SispopNetwork/'

# Google Analytics
# nope

# Extensions
markdown_extensions:
  - admonition
  - meta
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
